raj_friend_1_birthday = ("15th December")
raj_friend_2_birthday = ("23rd August")
raj_friend_3_birthday = ("4th November")
raj_friend_4_birthday = ("3rd July")
raj_friend_5_birthday = ("1st January")
raj_friend_1 = ("Rehan")
raj_friend_2 = ("Shrey")
raj_friend_3 = ("Aarav")
raj_friend_4 = ("Hriday")
raj_friend_5 = ("Ahaan")
print("Raj's friends and their birthdays:",raj_friend_1,"'s birthday is ",raj_friend_1_birthday,raj_friend_2,"'s birthday is",raj_friend_2_birthday,raj_friend_3,"'s birthday is",raj_friend_3_birthday,raj_friend_4,"'s birthday is",raj_friend_4_birthday,raj_friend_5,"'s birthday is",raj_friend_5_birthday)